import type { CandidateProfile, NormalizedJob, RankedJob, WorkPreference } from './jobMatch.js';
const keys = () => [process.env.GEMINI_KEY_1, process.env.GEMINI_KEY_2, process.env.GEMINI_KEY_3].filter((key): key is string => Boolean(key));
function json(text: string) { const match = text.match(/\{[\s\S]*\}/); return JSON.parse(match?.[0] || text); }
export async function understandAndRank(resumeText: string, baseProfile: CandidateProfile, jobs: NormalizedJob[], requestedLocation = '', workPreference: WorkPreference = 'both'): Promise<{ profile: CandidateProfile; jobs: RankedJob[] }> {
  const prompt = `Return JSON only. Build a candidate profile from this resume and rank only these supplied jobs. Never invent facts. The requested location is "${requestedLocation || 'any'}" and the requested work preference is "${workPreference}". Location eligibility was already enforced before this request: do not infer, relax, or reinterpret location. Rank only the supplied jobs and use each job's explicit location. Schema: {"profile":{"education":[],"experienceLevel":"","yearsExperience":null,"technicalSkills":[],"programmingLanguages":[],"frameworks":[],"softSkills":[],"industries":[],"preferredLocations":[],"remotePreference":"","employmentPreference":"","jobTitles":[],"careerLevel":"","projects":[],"certifications":[]},"rankings":[{"id":"","matchPercent":0,"reasons":[],"missingSkills":[],"strengths":[],"potentialSalaryFit":"","careerGrowth":"","likelihoodOfInterview":""}]}. Resume: ${resumeText.slice(0, 12000)}. Deterministic profile: ${JSON.stringify(baseProfile)}. Jobs: ${JSON.stringify(jobs.map(({ id,title,company,location,salary,description,tags,employmentType }) => ({ id,title,company,location,salary,description:description.slice(0,1800),tags,employmentType })) )}`;
  let last: unknown;
  if (!keys().length) throw new Error('No Gemini API keys are configured');
  const model = process.env.GEMINI_JOB_MATCH_MODEL || 'gemini-2.5-pro';
  for (const key of keys()) try { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }], generationConfig: { responseMimeType: 'application/json', temperature: 0.15 } }), signal: AbortSignal.timeout(45000) }); if (!response.ok) { const detail = (await response.text()).slice(0, 300); console.error('[gemini-job-match] provider response', { status: response.status, model, detail }); last = new Error(`Gemini ${response.status}`); if (response.status === 429 || response.status >= 500) continue; throw last; } const body = await response.json() as any; const parsed = json(body.candidates?.[0]?.content?.parts?.[0]?.text || '') as any; const byId = new Map<string, any>((parsed.rankings || []).map((r: any) => [r.id, r])); return { profile: { ...baseProfile, ...(parsed.profile || {}) }, jobs: jobs.map((job) => ({ ...job, matchPercent: Math.max(0, Math.min(100, Number(byId.get(job.id)?.matchPercent) || 0)), reasons: byId.get(job.id)?.reasons || [], missingSkills: byId.get(job.id)?.missingSkills || [], strengths: byId.get(job.id)?.strengths || [], potentialSalaryFit: byId.get(job.id)?.potentialSalaryFit || 'Not enough salary data', careerGrowth: byId.get(job.id)?.careerGrowth || 'Review role scope', likelihoodOfInterview: byId.get(job.id)?.likelihoodOfInterview || 'Not assessed' })).sort((a,b) => b.matchPercent-a.matchPercent) }; } catch (error) { last = error; }
  throw last instanceof Error ? last : new Error('Gemini ranking unavailable');
}
