import { parseResumeText } from './resumeParser.js';

export type JobSource = 'adzuna' | 'arbeitnow' | 'remoteok';
export type NormalizedJob = { id: string; source: JobSource; title: string; company: string; location: string; remoteType: 'Remote' | 'Hybrid' | 'Onsite' | 'Unknown'; salary: string; description: string; tags: string[]; applyUrl: string; employmentType: string };
export type CandidateProfile = { education: string[]; experienceLevel: string; yearsExperience: number | null; technicalSkills: string[]; programmingLanguages: string[]; frameworks: string[]; softSkills: string[]; industries: string[]; preferredLocations: string[]; remotePreference: string; employmentPreference: string; jobTitles: string[]; careerLevel: string; projects: string[]; certifications: string[] };
export type RankedJob = NormalizedJob & { matchPercent: number; reasons: string[]; missingSkills: string[]; strengths: string[]; potentialSalaryFit: string; careerGrowth: string; likelihoodOfInterview: string };

const clean = (value: unknown) => String(value || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
const remoteType = (job: Pick<NormalizedJob, 'location' | 'tags' | 'title' | 'description'>): NormalizedJob['remoteType'] => /hybrid/i.test(`${job.location} ${job.tags.join(' ')} ${job.description}`) ? 'Hybrid' : /remote|worldwide|anywhere/i.test(`${job.location} ${job.tags.join(' ')} ${job.title} ${job.description}`) ? 'Remote' : job.location ? 'Onsite' : 'Unknown';
const dedupe = (jobs: NormalizedJob[]) => Object.values(jobs.reduce<Record<string, NormalizedJob>>((out, job) => { const key = `${job.title}|${job.company}|${job.location}`.toLowerCase().replace(/\W/g, ''); if (!out[key] || job.description.length > out[key].description.length) out[key] = job; return out; }, {}));

export async function fetchAdzuna(query: string, location: string): Promise<NormalizedJob[]> {
  const id = process.env.ADZUNA_APP_ID; const key = process.env.ADZUNA_APP_KEY;
  if (!id || !key) return [];
  const country = (process.env.ADZUNA_COUNTRY || 'us').toLowerCase();
  const url = new URL(`https://api.adzuna.com/v1/api/jobs/${country}/search/1`);
  url.searchParams.set('app_id', id); url.searchParams.set('app_key', key); url.searchParams.set('what', query); if (location) url.searchParams.set('where', location); url.searchParams.set('results_per_page', '30');
  const response = await fetch(url, { signal: AbortSignal.timeout(9000) }); if (!response.ok) throw new Error(`Adzuna ${response.status}`);
  const data = await response.json() as { results?: any[] };
  return (data.results || []).map((item) => { const job = { id: `adzuna:${item.id}`, source: 'adzuna' as const, title: clean(item.title), company: clean(item.company?.display_name), location: clean(item.location?.display_name), salary: item.salary_min ? `${item.salary_min}${item.salary_max ? `–${item.salary_max}` : '+'}` : '', description: clean(item.description), tags: [], applyUrl: String(item.redirect_url || ''), employmentType: clean(item.contract_type || item.contract_time || '') }; return { ...job, remoteType: remoteType(job) }; });
}
export async function fetchArbeitnow(): Promise<NormalizedJob[]> { const r = await fetch('https://www.arbeitnow.com/api/job-board-api', { signal: AbortSignal.timeout(9000) }); if (!r.ok) throw new Error(`Arbeitnow ${r.status}`); const d = await r.json() as { data?: any[] }; return (d.data || []).map((x) => { const job = { id: `arbeitnow:${x.slug || x.url}`, source: 'arbeitnow' as const, title: clean(x.title), company: clean(x.company_name), location: clean(x.location), salary: '', description: clean(x.description), tags: Array.isArray(x.tags) ? x.tags.map(clean) : [], applyUrl: String(x.url || ''), employmentType: clean(x.job_types?.join(' ') || '') }; return { ...job, remoteType: remoteType(job) }; }); }
export async function fetchRemoteOk(): Promise<NormalizedJob[]> { const r = await fetch('https://remoteok.com/api', { headers: { 'User-Agent': 'ResuV Job Match' }, signal: AbortSignal.timeout(9000) }); if (!r.ok) throw new Error(`RemoteOK ${r.status}`); const d = await r.json() as any[]; return (d || []).filter((x) => x?.position).map((x) => { const job = { id: `remoteok:${x.id || x.url}`, source: 'remoteok' as const, title: clean(x.position), company: clean(x.company), location: clean(x.location || 'Remote'), salary: clean(x.salary), description: clean(x.description), tags: Array.isArray(x.tags) ? x.tags.map(clean) : [], applyUrl: String(x.url || ''), employmentType: 'Full Time' }; return { ...job, remoteType: 'Remote' as const }; }); }
export async function searchJobs(query: string, location: string) { const settled = await Promise.allSettled([fetchAdzuna(query, location), fetchArbeitnow(), fetchRemoteOk()]); return { jobs: dedupe(settled.flatMap((item) => item.status === 'fulfilled' ? item.value : [])).slice(0, 75), sources: settled.map((item, i) => ({ source: ['adzuna', 'arbeitnow', 'remoteok'][i], available: item.status === 'fulfilled' })) }; }
export function localProfile(resumeText: string): CandidateProfile { const r = parseResumeText(resumeText); return { education: r.education, experienceLevel: r.experience.length ? 'Experienced' : r.projects.length ? 'Early career' : 'Entry level', yearsExperience: null, technicalSkills: r.skills, programmingLanguages: r.technicalKeywords.programmingLanguages, frameworks: r.technicalKeywords.frameworks, softSkills: r.skillCategories.softSkills, industries: r.understanding.inferredProfiles.map((x) => x.role), preferredLocations: [], remotePreference: 'Open', employmentPreference: 'Open', jobTitles: [], careerLevel: r.experience.length ? 'Professional' : 'Student / Graduate', projects: r.projects.slice(0, 10), certifications: r.certifications }; }
